project_id = "pbsdsdexayzfoexjdlgb"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[functions.projects-api]

[functions.kanban-api]

[functions.auth-security]

[functions.chat-api]

[functions.dify-client]

[functions.feedback-api]

[functions.file-api]

[functions.file-validation]

[functions.import-history]

[functions.login-fix]

[functions.news-reply]

[functions.refresh]

[functions.stt-api]

[functions.tts-api]