import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.2';
import { handleCors } from '../_shared/cors.ts';
import { SafeTextSchema, UUIDSchema, validateInput } from '../_shared/validation.ts';
import { z } from "https://deno.land/x/zod@v3.22.4/mod.ts";

// Валідаційні схеми
const CreateFolderSchema = z.object({
  name: SafeTextSchema(200, 1),
  parentId: UUIDSchema.nullable().optional(),
  projectId: UUIDSchema.nullable().optional(),
  scope: z.enum(['community', 'project']).optional(),
});

const CreateFileSchema = z.object({
  name: SafeTextSchema(500, 1),
  fileType: z.string().max(50).optional(),
  mimeType: z.string().max(100).optional(),
  sizeBytes: z.number().int().positive().optional(),
  storagePath: z.string().max(1000).optional(),
  difyFileId: z.string().max(200).optional(),
  folderId: UUIDSchema.nullable().optional(),
  projectId: UUIDSchema.nullable().optional(),
  scope: z.enum(['community', 'project']).optional(),
  description: SafeTextSchema(2000, 0).optional(),
  tags: z.array(z.string().max(50)).optional(),
  autoGeneratedTags: z.boolean().optional(),
});

const UpdateFileMetadataSchema = z.object({
  name: SafeTextSchema(500, 1).optional(),
  description: SafeTextSchema(2000, 0).optional(),
  isKnowledgeBase: z.boolean().optional(),
  folderId: UUIDSchema.nullable().optional(),
  tags: z.array(z.string().max(50)).optional(),
});

const getRouteParts = (url: URL) => {
  const parts = url.pathname.split('/').filter(Boolean);
  return parts[0] === 'knowledge-base-api' ? parts.slice(1) : parts;
};

const enrichUploadedByProfiles = async (supabase: any, files: any[]) => {
  const userIds = [...new Set(files.map((file) => file.uploaded_by).filter(Boolean))];
  if (userIds.length === 0) return files;

  const { data: profiles, error } = await supabase.rpc('get_public_profiles', {
    p_user_ids: userIds,
  });

  if (error) {
    console.error('Error fetching file uploader profiles:', error);
    return files;
  }

  const profileByUserId = new Map(
    (profiles ?? []).map((profile: any) => [
      profile.user_id,
      {
        display_name: profile.display_name,
        avatar_url: profile.avatar_url,
      },
    ]),
  );

  return files.map((file) => ({
    ...file,
    profiles: file.uploaded_by ? profileByUserId.get(file.uploaded_by) ?? null : null,
  }));
};

serve(async (req) => {
  // Handle CORS
  const corsResult = handleCors(req);
  if (corsResult instanceof Response) {
    return corsResult;
  }
  const { headers } = corsResult;

  try {
    // JWT верифікація
    const authHeader = req.headers.get('authorization');
    if (!authHeader) {
      return new Response(
        JSON.stringify({ error: 'Відсутній токен авторизації' }),
        { status: 401, headers: { ...headers, 'Content-Type': 'application/json' } }
      );
    }

    // Створюємо клієнт з ANON_KEY та JWT токеном
    const supabase = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_ANON_KEY') ?? '',
      {
        global: {
          headers: { Authorization: authHeader },
        },
      }
    );

    // Верифікуємо користувача
    const { data: { user }, error: authError } = await supabase.auth.getUser();
    
    if (authError || !user) {
      return new Response(
        JSON.stringify({ error: 'Невірний або прострочений токен' }),
        { status: 401, headers: { ...headers, 'Content-Type': 'application/json' } }
      );
    }

    // Service role для специфічних операцій (AI agent permissions)
    const serviceSupabase = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    );

    const url = new URL(req.url);
    const method = req.method;
    const pathParts = getRouteParts(url);

    // GET /search - поиск файлов
    if (method === 'GET' && pathParts[0] === 'search') {
      const query = url.searchParams.get('q') || '';
      const scope = url.searchParams.get('scope');
      const projectId = url.searchParams.get('projectId');
      const tags = url.searchParams.get('tags')?.split(',').filter(Boolean) || [];
      const fileType = url.searchParams.get('fileType');
      
      // Валідація параметрів
      if (query.length > 500) {
        return new Response(
          JSON.stringify({ error: 'Запит занадто довгий (максимум 500 символів)' }),
          { status: 400, headers: { ...headers, 'Content-Type': 'application/json' } }
        );
      }
      
      let dbQuery = supabase
        .from('files')
        .select(`
          *,
          file_tags(tag),
          folders(name),
          conversations:project_id(name)
        `)
        .is('deleted_at', null);
      
      if (query) {
        // Sanitize user input to prevent PostgREST filter injection.
        // Strip PostgREST-significant characters (comma, parentheses, period,
        // asterisk, backslash) so the query text cannot alter filter logic.
        const safeQuery = query.replace(/[,()*.\\]/g, ' ').trim();
        if (safeQuery) {
          dbQuery = dbQuery.or(
            `name.ilike.%${safeQuery}%,description.ilike.%${safeQuery}%`,
          );
        }
      }
      
      if (scope) {
        dbQuery = dbQuery.eq('scope', scope);
      }
      
      if (projectId) {
        // Валідація UUID
        if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(projectId)) {
          return new Response(
            JSON.stringify({ error: 'Невірний формат projectId' }),
            { status: 400, headers: { ...headers, 'Content-Type': 'application/json' } }
          );
        }
        dbQuery = dbQuery.eq('project_id', projectId);
      }
      
      if (fileType) {
        dbQuery = dbQuery.eq('file_type', fileType);
      }
      
      const { data: files, error } = await dbQuery.order('created_at', { ascending: false });
      
      if (error) throw error;
      
      // Фильтр по тегам на клиенте
      let filteredFiles = files ?? [];
      if (tags.length > 0) {
        filteredFiles = filteredFiles.filter((file: any) => {
          const fileTags = file.file_tags?.map((t: any) => t.tag) || [];
          return tags.some(tag => fileTags.includes(tag));
        });
      }

      filteredFiles = await enrichUploadedByProfiles(supabase, filteredFiles);
      
      return new Response(JSON.stringify({ files: filteredFiles }), {
        headers: { ...headers, 'Content-Type': 'application/json' },
      });
    }

    // GET /folders - получение структуры папок
    if (method === 'GET' && pathParts[0] === 'folders') {
      const scope = url.searchParams.get('scope');
      const projectId = url.searchParams.get('projectId');
      
      let query = supabase
        .from('folders')
        .select('*')
        .order('name');
      
      if (scope) {
        query = query.eq('scope', scope);
      }
      
      if (projectId) {
        if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(projectId)) {
          return new Response(
            JSON.stringify({ error: 'Невірний формат projectId' }),
            { status: 400, headers: { ...headers, 'Content-Type': 'application/json' } }
          );
        }
        query = query.eq('project_id', projectId);
      }
      
      const { data, error } = await query;
      
      if (error) throw error;
      
      return new Response(JSON.stringify({ folders: data }), {
        headers: { ...headers, 'Content-Type': 'application/json' },
      });
    }

    // POST /folders - создание папки
    if (method === 'POST' && pathParts[0] === 'folders') {
      const body = await req.json();
      
      // Валідація вводу
      const validationResult = validateInput(CreateFolderSchema, body);
      if (!validationResult.success) {
        return new Response(
          JSON.stringify({ 
            error: 'Помилка валідації',
            details: validationResult.error.errors 
          }),
          { status: 400, headers: { ...headers, 'Content-Type': 'application/json' } }
        );
      }

      const { data, error } = await supabase
        .from('folders')
        .insert({
          name: validationResult.data.name,
          parent_id: validationResult.data.parentId || null,
          project_id: validationResult.data.projectId || null,
          scope: validationResult.data.scope || 'community',
          created_by: user.id,
        })
        .select()
        .single();
      
      if (error) throw error;
      
      return new Response(JSON.stringify({ folder: data }), {
        headers: { ...headers, 'Content-Type': 'application/json' },
      });
    }

    // GET /{fileId} - получение информации о файле
    if (method === 'GET' && pathParts.length === 1) {
      const fileId = pathParts[0];
      
      // Валідація UUID
      if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(fileId)) {
        return new Response(
          JSON.stringify({ error: 'Невірний формат ID файлу' }),
          { status: 400, headers: { ...headers, 'Content-Type': 'application/json' } }
        );
      }
      
      const { data, error } = await supabase
        .from('files')
        .select(`
          *,
          file_tags(tag, auto_generated),
          file_versions(version_number, created_at, uploaded_by, change_note),
          folders(name),
          conversations:project_id(name)
        `)
        .eq('id', fileId)
        .single();
      
      if (error) throw error;
      
      const [fileWithProfile] = await enrichUploadedByProfiles(supabase, data ? [data] : []);

      return new Response(JSON.stringify({ file: fileWithProfile ?? data }), {
        headers: { ...headers, 'Content-Type': 'application/json' },
      });
    }

    // POST /create - создание файла AI-агентом
    if (method === 'POST' && pathParts[0] === 'create') {
      const body = await req.json();
      
      // Валідація вводу
      const validationResult = validateInput(CreateFileSchema, body);
      if (!validationResult.success) {
        return new Response(
          JSON.stringify({ 
            error: 'Помилка валідації',
            details: validationResult.error.errors 
          }),
          { status: 400, headers: { ...headers, 'Content-Type': 'application/json' } }
        );
      }

      // Проверка прав AI-агента
      const { data: permissions } = await serviceSupabase.rpc('get_ai_agent_permissions', {
        p_scope: validationResult.data.scope || 'community',
        p_project_id: validationResult.data.projectId,
        p_folder_id: validationResult.data.folderId,
      });
      
      if (!permissions || !permissions[0]?.can_write) {
        return new Response(
          JSON.stringify({ error: 'AI agent has no write permission' }),
          {
            status: 403,
            headers: { ...headers, 'Content-Type': 'application/json' },
          }
        );
      }
      
      const { data, error } = await supabase
        .from('files')
        .insert({
          name: validationResult.data.name,
          file_type: validationResult.data.fileType || 'other',
          mime_type: validationResult.data.mimeType,
          size_bytes: validationResult.data.sizeBytes,
          storage_path: validationResult.data.storagePath,
          dify_file_id: validationResult.data.difyFileId,
          folder_id: validationResult.data.folderId || null,
          project_id: validationResult.data.projectId || null,
          scope: validationResult.data.scope || 'community',
          description: validationResult.data.description,
          uploaded_by: user.id,
        })
        .select()
        .single();
      
      if (error) throw error;
      
      // Добавить теги, если есть
      if (validationResult.data.tags && validationResult.data.tags.length > 0) {
        await supabase.from('file_tags').insert(
          validationResult.data.tags.map((tag: string) => ({
            file_id: data.id,
            tag,
            added_by: user.id,
            auto_generated: validationResult.data.autoGeneratedTags || false,
          }))
        );
      }
      
      return new Response(JSON.stringify({ file: data }), {
        headers: { ...headers, 'Content-Type': 'application/json' },
      });
    }

    // PUT /{fileId}/metadata - обновление метаданных
    if (method === 'PUT' && pathParts[1] === 'metadata') {
      const fileId = pathParts[0];
      
      // Валідація UUID
      if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(fileId)) {
        return new Response(
          JSON.stringify({ error: 'Невірний формат ID файлу' }),
          { status: 400, headers: { ...headers, 'Content-Type': 'application/json' } }
        );
      }

      const body = await req.json();
      
      // Валідація вводу
      const validationResult = validateInput(UpdateFileMetadataSchema, body);
      if (!validationResult.success) {
        return new Response(
          JSON.stringify({ 
            error: 'Помилка валідації',
            details: validationResult.error.errors 
          }),
          { status: 400, headers: { ...headers, 'Content-Type': 'application/json' } }
        );
      }
      
      const updates: any = {};
      if (validationResult.data.name) updates.name = validationResult.data.name;
      if (validationResult.data.description !== undefined) updates.description = validationResult.data.description;
      if (validationResult.data.isKnowledgeBase !== undefined) updates.is_knowledge_base = validationResult.data.isKnowledgeBase;
      if (validationResult.data.folderId !== undefined) updates.folder_id = validationResult.data.folderId;
      
      const { data, error } = await supabase
        .from('files')
        .update(updates)
        .eq('id', fileId)
        .select()
        .single();
      
      if (error) throw error;
      
      // Обновить теги, если есть
      if (validationResult.data.tags) {
        // Удалить старые теги
        await supabase.from('file_tags').delete().eq('file_id', fileId);
        
        // Добавить новые
        if (validationResult.data.tags.length > 0) {
          await supabase.from('file_tags').insert(
            validationResult.data.tags.map((tag: string) => ({
              file_id: fileId,
              tag,
              added_by: user.id,
            }))
          );
        }
      }
      
      return new Response(JSON.stringify({ file: data }), {
        headers: { ...headers, 'Content-Type': 'application/json' },
      });
    }

    // POST /{fileId}/version - создание новой версии
    if (method === 'POST' && pathParts[1] === 'version') {
      const fileId = pathParts[0];
      
      // Валідація UUID
      if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(fileId)) {
        return new Response(
          JSON.stringify({ error: 'Невірний формат ID файлу' }),
          { status: 400, headers: { ...headers, 'Content-Type': 'application/json' } }
        );
      }

      const body = await req.json();
      
      // Валідація вводу
      const VersionSchema = z.object({
        storagePath: z.string().max(1000),
        sizeBytes: z.number().int().positive(),
        changeNote: SafeTextSchema(500, 0).optional(),
      });
      
      const validationResult = validateInput(VersionSchema, body);
      if (!validationResult.success) {
        return new Response(
          JSON.stringify({ 
            error: 'Помилка валідації',
            details: validationResult.error.errors 
          }),
          { status: 400, headers: { ...headers, 'Content-Type': 'application/json' } }
        );
      }
      
      // Получить текущую версию
      const { data: versions } = await supabase
        .from('file_versions')
        .select('version_number')
        .eq('file_id', fileId)
        .order('version_number', { ascending: false })
        .limit(1);
      
      const nextVersion = versions && versions.length > 0 ? versions[0].version_number + 1 : 1;
      
      const { data, error } = await supabase
        .from('file_versions')
        .insert({
          file_id: fileId,
          version_number: nextVersion,
          storage_path: validationResult.data.storagePath,
          size_bytes: validationResult.data.sizeBytes,
          uploaded_by: user.id,
          change_note: validationResult.data.changeNote,
        })
        .select()
        .single();
      
      if (error) throw error;
      
      return new Response(JSON.stringify({ version: data }), {
        headers: { ...headers, 'Content-Type': 'application/json' },
      });
    }

    // DELETE /{fileId} - удаление файла (soft delete)
    if (method === 'DELETE' && pathParts.length === 1) {
      const fileId = pathParts[0];
      
      // Валідація UUID
      if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(fileId)) {
        return new Response(
          JSON.stringify({ error: 'Невірний формат ID файлу' }),
          { status: 400, headers: { ...headers, 'Content-Type': 'application/json' } }
        );
      }
      
      // Проверка прав AI-агента, если запрос от агента
      const isAIAgent = req.headers.get('x-ai-agent') === 'true';
      
      if (isAIAgent) {
        const { data: file } = await supabase
          .from('files')
          .select('scope, project_id, folder_id')
          .eq('id', fileId)
          .single();
        
        if (file) {
          const { data: permissions } = await serviceSupabase.rpc('get_ai_agent_permissions', {
            p_scope: file.scope,
            p_project_id: file.project_id,
            p_folder_id: file.folder_id,
          });
          
          if (!permissions || !permissions[0]?.can_delete) {
            return new Response(
              JSON.stringify({ error: 'AI agent has no delete permission' }),
              {
                status: 403,
                headers: { ...headers, 'Content-Type': 'application/json' },
              }
            );
          }
        }
      }
      
      const { error } = await supabase
        .from('files')
        .update({ deleted_at: new Date().toISOString() })
        .eq('id', fileId);
      
      if (error) throw error;
      
      return new Response(JSON.stringify({ success: true }), {
        headers: { ...headers, 'Content-Type': 'application/json' },
      });
    }

    return new Response(
      JSON.stringify({ error: 'Маршрут не знайдено' }),
      { status: 404, headers: { ...headers, 'Content-Type': 'application/json' } }
    );

  } catch (error) {
    console.error('Error in knowledge-base-api:', error);
    return new Response(
      JSON.stringify({ 
        error: 'Внутрішня помилка сервера',
        details: error instanceof Error ? error.message : 'Unknown error' 
      }),
      {
        status: 500,
        headers: { ...headers, 'Content-Type': 'application/json' },
      }
    );
  }
});
