import { supabase } from "@/integrations/supabase/client";
import { translations, Language } from "@/lib/i18n";

type PublicProfile = {
  user_id: string;
  display_name: string | null;
  avatar_url: string | null;
};

const getTranslation = () => {
  const saved = typeof window !== 'undefined' ? localStorage.getItem('language') : null;
  const lang = (saved && ['uk', 'en', 'ru', 'es'].includes(saved) ? saved : 'uk') as Language;
  return translations[lang];
};

export interface ChatParticipant {
  user_id: string;
  display_name: string;
  avatar_url?: string | null;
  role?: string | null;
  joined_at?: string;
  last_read_at?: string | null;
}

export interface ChatLite {
  id: string;
  name: string;
  lastMessagePreview?: string;
  messageCount?: number;
  createdAt?: string;
  updatedAt?: string;
  status?: string | null;
  is_pinned?: boolean;
  pinned_at?: string;
  auto_generated_name?: boolean;
  participants?: ChatParticipant[];
  onlineCount?: number;
  dify_conversation_id?: string;
  forked_from_chat?: string;
}

const normalizeChatName = (name: string, isAutoGenerated?: boolean | null) => {
  if (!isAutoGenerated) return name;
  const t = getTranslation();
  const defaultNames = [
    translations.uk.chatSidebar.defaultChatName,
    translations.en.chatSidebar.defaultChatName,
    translations.ru.chatSidebar.defaultChatName,
    translations.es.chatSidebar.defaultChatName,
  ];
  return defaultNames.includes(name)
    ? t.chatSidebar.defaultChatName
    : name;
};

const buildProfileMap = (profiles: PublicProfile[] | null | undefined) =>
  new Map((profiles || []).map(profile => [profile.user_id, profile]));

const fetchPublicProfiles = async (userIds: string[]) => {
  const uniqueIds = [...new Set(userIds.filter(Boolean))];
  if (uniqueIds.length === 0) return new Map<string, PublicProfile>();

  const { data, error } = await supabase.rpc('get_public_profiles', {
    p_user_ids: uniqueIds,
  });

  if (error) {
    console.warn('Unable to load public participant profiles:', error.message);
    return new Map<string, PublicProfile>();
  }

  return buildProfileMap(data);
};

const getParticipantFallbackName = (userId: string) => {
  const t = getTranslation();
  return `${t.participantsExtra.userFallbackName} ${userId.slice(0, 6)}`;
};

const createParticipants = (
  rows: Array<{
    user_id: string;
    role?: string | null;
    joined_at?: string;
    last_read_at?: string | null;
  }>,
  profilesById: Map<string, PublicProfile>,
): ChatParticipant[] =>
  rows.map(row => {
    const profile = profilesById.get(row.user_id);
    return {
      user_id: row.user_id,
      display_name: profile?.display_name || getParticipantFallbackName(row.user_id),
      avatar_url: profile?.avatar_url,
      role: row.role,
      joined_at: row.joined_at,
      last_read_at: row.last_read_at,
    };
  });

const createMessagePreview = (message: {
  content: string;
  role: string;
  message_type?: string | null;
}) => {
  const t = getTranslation();
  if (message.message_type === 'voice') return t.chatInterface.voiceMessagePreview;
  if (message.message_type === 'file') return t.chatInterface.fileMessagePreview;

  const prefix = message.role === 'assistant'
    ? t.chatPage.agentFallbackName
    : message.role === 'user'
      ? t.chatPage.userFallbackName
      : '';
  const content = message.content.trim().replace(/\s+/g, ' ');
  const preview = content.length > 90 ? `${content.slice(0, 90)}...` : content;
  return prefix ? `${prefix}: ${preview}` : preview;
};

export async function ensureCurrentUserParticipant(chatId: string): Promise<string | null> {
  const { data: { user }, error: authError } = await supabase.auth.getUser();
  if (authError || !user) return null;

  const { data: existing, error: existingError } = await supabase
    .from('conversation_participants')
    .select('id')
    .eq('conversation_id', chatId)
    .eq('user_id', user.id)
    .maybeSingle();

  if (existingError) {
    console.warn('Unable to check current chat participation:', existingError.message);
  }

  if (existing) return user.id;

  const { error: insertError } = await supabase
    .from('conversation_participants')
    .upsert({
      conversation_id: chatId,
      user_id: user.id,
      role: 'member',
    }, {
      onConflict: 'conversation_id,user_id',
      ignoreDuplicates: true,
    });

  if (insertError) {
    console.warn('Unable to repair current chat participation:', insertError.message);
  }

  return user.id;
}

export async function fetchChatParticipants(chatId: string): Promise<ChatParticipant[]> {
  const { data: participantRows, error } = await supabase
    .from('conversation_participants')
    .select('user_id, role, joined_at, last_read_at')
    .eq('conversation_id', chatId);

  if (error) {
    console.warn('Unable to load chat participants:', error.message);
    return [];
  }

  const profilesById = await fetchPublicProfiles((participantRows || []).map(row => row.user_id));
  return createParticipants(participantRows || [], profilesById);
}

export async function fetchChats(): Promise<ChatLite[]> {
  console.log('Fetching chats directly from Supabase...');
  
  const { data: conversations, error } = await supabase
    .from('conversations')
    .select('id, name, updated_at, created_at, dify_conversation_id, status, is_pinned, pinned_at, auto_generated_name, forked_from_chat')
    .eq('status', 'active')
    .order('updated_at', { ascending: false });

  if (error) {
    console.error('Error fetching chats:', error);
    throw new Error(`Failed to fetch chats: ${error.message}`);
  }

  const chatIds = (conversations || []).map(chat => chat.id);
  if (chatIds.length === 0) return [];

  const [{ data: participantRows }, { data: messageRows }] = await Promise.all([
    supabase
      .from('conversation_participants')
      .select('conversation_id, user_id, role, joined_at, last_read_at')
      .in('conversation_id', chatIds),
    supabase
      .from('messages')
      .select('id, conversation_id, content, role, message_type, created_at')
      .in('conversation_id', chatIds)
      .is('parent_id', null)
      .is('deleted_at', null)
      .order('created_at', { ascending: false })
      .limit(500),
  ]);

  const profilesById = await fetchPublicProfiles((participantRows || []).map(row => row.user_id));
  const participantsByChat = new Map<string, ChatParticipant[]>();
  (participantRows || []).forEach(row => {
    const current = participantsByChat.get(row.conversation_id) || [];
    current.push(...createParticipants([row], profilesById));
    participantsByChat.set(row.conversation_id, current);
  });

  const latestMessageByChat = new Map<string, NonNullable<typeof messageRows>[number]>();
  const messageCountByChat = new Map<string, number>();
  (messageRows || []).forEach(row => {
    messageCountByChat.set(row.conversation_id, (messageCountByChat.get(row.conversation_id) || 0) + 1);
    if (!latestMessageByChat.has(row.conversation_id)) {
      latestMessageByChat.set(row.conversation_id, row);
    }
  });

  return (conversations || []).map(conv => ({
    id: conv.id,
    name: normalizeChatName(conv.name, conv.auto_generated_name),
    createdAt: conv.created_at,
    updatedAt: conv.updated_at,
    status: conv.status,
    lastMessagePreview: latestMessageByChat.has(conv.id)
      ? createMessagePreview(latestMessageByChat.get(conv.id)!)
      : '',
    messageCount: messageCountByChat.get(conv.id) || 0,
    is_pinned: conv.is_pinned,
    pinned_at: conv.pinned_at,
    auto_generated_name: conv.auto_generated_name,
    dify_conversation_id: conv.dify_conversation_id,
    forked_from_chat: conv.forked_from_chat || undefined,
    participants: participantsByChat.get(conv.id) || [],
    onlineCount: 0,
  }));
}

export async function createChat(name: string): Promise<ChatLite> {
  console.log('Creating chat directly with Supabase...', { name });
  
  const { data: { user }, error: authError } = await supabase.auth.getUser();
  
  if (authError || !user) {
    console.error('Authentication error:', authError);
    throw new Error('You must be logged in to create a chat');
  }

  console.log('Authenticated user for chat creation:', user.id);

  // Create conversation
  console.log('Inserting conversation into database...');
  const t = getTranslation();
  const { data: newChat, error } = await supabase
    .from('conversations')
    .insert({
      name: name || t.chatSidebar.defaultChatName,
      user_id: user.id,
      created_by: user.id,
      status: 'active'
    })
    .select('id, name, created_at, updated_at')
    .single();

  if (error) {
    console.error('Error creating chat:', error);
    throw new Error(`Failed to create chat: ${error.message}`);
  }

  console.log('Conversation created successfully:', newChat);

  // Add user as conversation participant (required for RLS policies)
  console.log('Adding participant to conversation...');
  const { error: participantError } = await supabase
    .from('conversation_participants')
    .insert({
      conversation_id: newChat.id,
      user_id: user.id,
      role: 'member'
    });

  if (participantError) {
    console.error('Error adding user as participant:', participantError);
    // Try to clean up the conversation if participant insertion failed
    await supabase.from('conversations').delete().eq('id', newChat.id);
    throw new Error(`Failed to create chat: ${participantError.message}`);
  }

  console.log('Created chat with participant:', newChat);

  return {
    id: newChat.id,
    name: normalizeChatName(newChat.name, true),
    createdAt: newChat.created_at,
    updatedAt: newChat.updated_at,
    lastMessagePreview: '',
    messageCount: 0,
    dify_conversation_id: undefined,
    forked_from_chat: undefined,
    participants: [{
      user_id: user.id,
      display_name: user.user_metadata?.display_name || user.email?.split('@')[0] || t.participantsExtra.userFallbackName,
      avatar_url: user.user_metadata?.avatar_url,
      role: 'member',
    }],
    onlineCount: 0,
  };
}

// Archive a chat (move from active to archived)
export async function archiveChat(chatId: string): Promise<void> {
  const { error } = await supabase
    .from('conversations')
    .update({ status: 'archived' })
    .eq('id', chatId);

  if (error) {
    throw new Error(`Failed to archive chat: ${error.message}`);
  }
}

// Delete a chat permanently (move to deleted status)
export async function deleteChat(chatId: string): Promise<void> {
  const { error } = await supabase
    .from('conversations')
    .update({ status: 'deleted' })
    .eq('id', chatId);

  if (error) {
    throw new Error(`Failed to delete chat: ${error.message}`);
  }
}

// Restore a chat from archive
export async function restoreChat(chatId: string): Promise<void> {
  const { error } = await supabase
    .from('conversations')
    .update({ status: 'active' })
    .eq('id', chatId);

  if (error) {
    throw new Error(`Failed to restore chat: ${error.message}`);
  }
}

// Fetch chats by status
export const renameChat = async (chatId: string, newName: string): Promise<void> => {
  const { error } = await supabase
    .from('conversations')
    .update({ 
      name: newName,
      auto_generated_name: false, // Отмечаем что название теперь не автогенерированное
      updated_at: new Date().toISOString()
    })
    .eq('id', chatId);

  if (error) {
    throw error;
  }
};

export const pinChat = async (chatId: string, pinned: boolean): Promise<void> => {
  const { error } = await supabase
    .from('conversations')
    .update({ 
      is_pinned: pinned,
      pinned_at: pinned ? new Date().toISOString() : null,
      updated_at: new Date().toISOString()
    })
    .eq('id', chatId);

  if (error) {
    throw error;
  }
};

export const deleteMessage = async (messageId: string): Promise<void> => {
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) throw new Error('Unauthorized');

  const { error } = await supabase.rpc('soft_delete_message', {
    p_message_id: messageId,
  });

  if (error) {
    throw error;
  }
};

// Генерация названия чата на основе первого сообщения
export const generateChatName = (firstMessage: string): string => {
  const t = getTranslation();
  if (!firstMessage.trim()) return t.chatSidebar.defaultChatName;
  
  const cleaned = firstMessage.trim().replace(/\n+/g, ' ');
  return cleaned.slice(0, 30) + (cleaned.length > 30 ? "..." : "");
};

// Генерация названия для ветки
export const generateBranchName = (parentMessage: string, parentChatName: string): string => {
  const t = getTranslation();
  const base = parentMessage.trim().slice(0, 20);
  const template = t.chatPage.forkedFromTitle;
  const branchName = template.replace('{name}', parentChatName);
  return `${branchName} (${base}...)`;
};

export async function fetchChatsByStatus(status: 'active' | 'archived' | 'deleted'): Promise<ChatLite[]> {
  const { data: conversations, error } = await supabase
    .from('conversations')
    .select('id, name, updated_at, created_at, dify_conversation_id, status, is_pinned, pinned_at, auto_generated_name')
    .eq('status', status)
    .order('updated_at', { ascending: false });

  if (error) {
    console.error('Error fetching chats by status:', error);
    throw new Error(`Failed to fetch chats: ${error.message}`);
  }

  return (conversations || []).map(conv => ({
    id: conv.id,
    name: normalizeChatName(conv.name, conv.auto_generated_name),
    createdAt: conv.created_at,
    updatedAt: conv.updated_at,
    status: conv.status,
    lastMessagePreview: '',
    messageCount: 0,
    is_pinned: conv.is_pinned,
    pinned_at: conv.pinned_at,
    auto_generated_name: conv.auto_generated_name,
    dify_conversation_id: conv.dify_conversation_id,
    forked_from_chat: undefined,
    participants: [],
    onlineCount: 0,
  }));
}
