// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/who-am-i.ts
import { createClient } from "npm:@supabase/supabase-js@^2.106.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
var who_am_i_default = defineTool({
  name: "who_am_i",
  title: "Who am I",
  description: "Return the signed-in user's id, email, and display name from their profile.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const userId = ctx.getUserId();
    const { data, error } = await supabase.from("profiles").select("display_name, email, role, avatar_url").eq("user_id", userId).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const payload = {
      user_id: userId,
      email: ctx.getUserEmail() ?? data?.email ?? null,
      display_name: data?.display_name ?? null,
      role: data?.role ?? null,
      avatar_url: data?.avatar_url ?? null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-my-conversations.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.106.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^4.4.3";
var list_my_conversations_default = defineTool2({
  name: "list_my_conversations",
  title: "List my conversations",
  description: "List the signed-in user's chat conversations, most recently updated first.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(20).describe("Max conversations to return (1-50)."),
    include_archived: z.boolean().default(false).describe("Whether to include archived conversations.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, include_archived }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    let query = supabase.from("conversations").select("id, name, type, is_group_chat, is_pinned, is_archived, status, updated_at, created_at").order("updated_at", { ascending: false }).limit(limit);
    if (!include_archived) query = query.eq("is_archived", false);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { conversations: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-conversation-messages.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.106.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^4.4.3";
var list_conversation_messages_default = defineTool3({
  name: "list_conversation_messages",
  title: "List messages in a conversation",
  description: "List messages from a conversation the signed-in user has access to, oldest to newest.",
  inputSchema: {
    conversation_id: z2.string().uuid().describe("The UUID of the conversation."),
    limit: z2.number().int().min(1).max(100).default(50).describe("Max messages to return (1-100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ conversation_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data, error } = await supabase.from("messages").select("id, conversation_id, role, sender_name, content, message_type, created_at, parent_id").eq("conversation_id", conversation_id).is("deleted_at", null).order("created_at", { ascending: true }).limit(limit);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { messages: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/send-message.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.106.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^4.4.3";
var send_message_default = defineTool4({
  name: "send_message",
  title: "Send message",
  description: "Send a message from the signed-in user into a conversation they participate in.",
  inputSchema: {
    conversation_id: z3.string().uuid().describe("The UUID of the conversation to post into."),
    content: z3.string().min(1).max(5e3).describe("Message text (1-5000 chars).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ conversation_id, content }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient4(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data, error } = await supabase.from("messages").insert({
      conversation_id,
      content,
      role: "user",
      message_type: "text"
    }).select("id, conversation_id, created_at").single();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Message sent (id: ${data.id})` }],
      structuredContent: { message: data }
    };
  }
});

// src/lib/mcp/tools/list-my-tasks.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.106.1";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z4 } from "npm:zod@^4.4.3";
var list_my_tasks_default = defineTool5({
  name: "list_my_tasks",
  title: "List my tasks",
  description: "List kanban tasks assigned to the signed-in user.",
  inputSchema: {
    limit: z4.number().int().min(1).max(100).default(50).describe("Max tasks to return (1-100)."),
    column_type: z4.string().nullable().default(null).describe("Optional kanban column filter (e.g. 'todo', 'in_progress', 'done'). Null returns all.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, column_type }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient5(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    let query = supabase.from("kanban_cards").select("id, project_id, title, description, column_type, due_date, created_at, updated_at").eq("assignee_id", ctx.getUserId()).order("updated_at", { ascending: false }).limit(limit);
    if (column_type) query = query.eq("column_type", column_type);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { tasks: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "hjquragwfmcrljanmhtt";
var mcp_default = defineMcp({
  name: "microdao-mcp",
  title: "MicroDAO / \u0416\u041E\u0421",
  version: "0.1.0",
  instructions: "Tools for the \u0416\u041E\u0421 MicroDAO app. Use who_am_i to confirm the signed-in user, list_my_conversations to browse chats, list_conversation_messages to read a chat, send_message to post a message as the user, and list_my_tasks to see kanban tasks assigned to the user. All tools respect row-level security and act as the authenticated user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    who_am_i_default,
    list_my_conversations_default,
    list_conversation_messages_default,
    send_message_default,
    list_my_tasks_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
